version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: voltzx
      POSTGRES_PASSWORD: voltzx123
      POSTGRES_DB: voltzx_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  api:
    build: .
    command: yarn start:dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://voltzx:voltzx123@postgres:5432/voltzx_db

volumes:
  postgres_data:
